export const games = [
  {
    _id: "621568afdcc02c6c468ce026",
    title: "God of War",
    price: 34.99,
    rating: 3.5,
    win: true,
    mac: true,
    linux: true,
    description:
      "Set 22 years after Dying Light, it stars a new protagonist named Aiden Caldwell (voiced by Jonah Scott), who is equipped with various parkour skills. Players can perform actions such as climbing ledges, sliding, leaping off from edges, and wall running to quickly navigate the city. It was confirmed that there are over 3000 parkour animations to give a more fluid free running experience. Tools such as a grappling hook and a paraglider also aid traversal in the city. Aiden can also use the undead to break his fall. The game is mostly melee-based with the majority of fighting using melee weapons. The melee weapons have a limited lifespan and will degrade as the player uses them in combat. Long-range weapons such as crossbows, shotguns, and spears can be used as well. Weapons can be upgraded with different blueprints and components which can be found by breaking down weapons for craft parts. Aiden can also utilize superhuman skills due to the infection. New zombies have been added. Like the first game, the zombies are slow when exposed to sunlight, but they become more aggressive and hostile at night. During the latter time of day, players can avoid zombies roaming the streets by staying on rooftops, who would otherwise hibernate inside buildings to avoid sunlight, or explore the safe interior of buildings to find items.",
    image: "http://images6.alphacoders.com/114/1148838.jpg",
    color: "#000000",
    id: "product_ce95b156-d016-4d08-840b-d82c6b8d5112",
    createdAt: "2022-02-22T22:50:23.885Z",
    updatedAt: "2022-02-22T22:50:23.885Z",
    __v: 0,
  },
  {
    _id: "621568afdcc02c6c468ce026",
    title: "Dying Light 2",
    price: 34.99,
    rating: 3.5,
    win: true,
    mac: true,
    linux: true,
    description:
      "Set 22 years after Dying Light, it stars a new protagonist named Aiden Caldwell (voiced by Jonah Scott), who is equipped with various parkour skills. Players can perform actions such as climbing ledges, sliding, leaping off from edges, and wall running to quickly navigate the city. It was confirmed that there are over 3000 parkour animations to give a more fluid free running experience. Tools such as a grappling hook and a paraglider also aid traversal in the city. Aiden can also use the undead to break his fall. The game is mostly melee-based with the majority of fighting using melee weapons. The melee weapons have a limited lifespan and will degrade as the player uses them in combat. Long-range weapons such as crossbows, shotguns, and spears can be used as well. Weapons can be upgraded with different blueprints and components which can be found by breaking down weapons for craft parts. Aiden can also utilize superhuman skills due to the infection. New zombies have been added. Like the first game, the zombies are slow when exposed to sunlight, but they become more aggressive and hostile at night. During the latter time of day, players can avoid zombies roaming the streets by staying on rooftops, who would otherwise hibernate inside buildings to avoid sunlight, or explore the safe interior of buildings to find items.",
    image: "http://images6.alphacoders.com/114/1148838.jpg",
    color: "#000000",
    id: "product_ce95b156-d016-4d08-840b-d82c6b8d5112",
    createdAt: "2022-02-22T22:50:23.885Z",
    updatedAt: "2022-02-22T22:50:23.885Z",
    __v: 0,
  },
  {
    _id: "621568afdcc02c6c468ce026",
    title: "Battlefield 2",
    price: 34.99,
    rating: 3.5,
    win: true,
    mac: true,
    linux: true,
    description:
      "Set 22 years after Dying Light, it stars a new protagonist named Aiden Caldwell (voiced by Jonah Scott), who is equipped with various parkour skills. Players can perform actions such as climbing ledges, sliding, leaping off from edges, and wall running to quickly navigate the city. It was confirmed that there are over 3000 parkour animations to give a more fluid free running experience. Tools such as a grappling hook and a paraglider also aid traversal in the city. Aiden can also use the undead to break his fall. The game is mostly melee-based with the majority of fighting using melee weapons. The melee weapons have a limited lifespan and will degrade as the player uses them in combat. Long-range weapons such as crossbows, shotguns, and spears can be used as well. Weapons can be upgraded with different blueprints and components which can be found by breaking down weapons for craft parts. Aiden can also utilize superhuman skills due to the infection. New zombies have been added. Like the first game, the zombies are slow when exposed to sunlight, but they become more aggressive and hostile at night. During the latter time of day, players can avoid zombies roaming the streets by staying on rooftops, who would otherwise hibernate inside buildings to avoid sunlight, or explore the safe interior of buildings to find items.",
    image: "http://images6.alphacoders.com/114/1148838.jpg",
    color: "#000000",
    id: "product_ce95b156-d016-4d08-840b-d82c6b8d5112",
    createdAt: "2022-02-22T22:50:23.885Z",
    updatedAt: "2022-02-22T22:50:23.885Z",
    __v: 0,
  },
  {
    _id: "621568afdcc02c6c468ce026",
    title: "Hoeizon forbidden west",
    price: 34.99,
    rating: 3.5,
    win: true,
    mac: true,
    linux: true,
    description:
      "Set 22 years after Dying Light, it stars a new protagonist named Aiden Caldwell (voiced by Jonah Scott), who is equipped with various parkour skills. Players can perform actions such as climbing ledges, sliding, leaping off from edges, and wall running to quickly navigate the city. It was confirmed that there are over 3000 parkour animations to give a more fluid free running experience. Tools such as a grappling hook and a paraglider also aid traversal in the city. Aiden can also use the undead to break his fall. The game is mostly melee-based with the majority of fighting using melee weapons. The melee weapons have a limited lifespan and will degrade as the player uses them in combat. Long-range weapons such as crossbows, shotguns, and spears can be used as well. Weapons can be upgraded with different blueprints and components which can be found by breaking down weapons for craft parts. Aiden can also utilize superhuman skills due to the infection. New zombies have been added. Like the first game, the zombies are slow when exposed to sunlight, but they become more aggressive and hostile at night. During the latter time of day, players can avoid zombies roaming the streets by staying on rooftops, who would otherwise hibernate inside buildings to avoid sunlight, or explore the safe interior of buildings to find items.",
    image: "http://images6.alphacoders.com/114/1148838.jpg",
    color: "#000000",
    id: "product_ce95b156-d016-4d08-840b-d82c6b8d5112",
    createdAt: "2022-02-22T22:50:23.885Z",
    updatedAt: "2022-02-22T22:50:23.885Z",
    __v: 0,
  },
];
